QUEUE_EMAIL_CREDENTIALS = "queue:email_credentials"

RATE_LIMIT_KEY_PREFIX = "credentials_rate:"
RATE_LIMIT_TTL_SECONDS = 60

CODE_EXPIRATION_SECONDS = 600 

BRUTE_FORCE_CODE_PREFIX = "bf_code:"
BRUTE_FORCE_CODE_MAX_ATTEMPTS = 3
BRUTE_FORCE_CODE_BLOCK_SECONDS = 360

BRUTE_FORCE_LOGIN_PREFIX = "bf_login:"
BRUTE_FORCE_LOGIN_MAX_ATTEMPTS = 3
BRUTE_FORCE_LOGIN_BLOCK_SECONDS = 360
