services:
  client_builder:
    build:
      context: ./Client
      dockerfile: dockerfile
    volumes:
      - client_assets:/app/static 
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    depends_on:
      client_builder:
        condition: service_completed_successfully
    ports:
      - "80:5000"
    env_file:
      - ./server/.env
    environment:
      - FLASK_ENV=production
      - PORT=5000
    volumes:
      - ./server:/app
      - ./Client/templates:/Client/templates
      - client_assets:/Client/static
    restart: always

volumes:
  client_assets: