FROM python:3.11-slim

WORKDIR /app

# Instalamos dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Variables de entorno para desarrollo
ENV FLASK_APP=server.py
ENV FLASK_ENV=development
ENV FLASK_DEBUG=1

EXPOSE 5000

# Ejecutamos Flask con el reloader activo y escuchando en todas las interfaces
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--reload"]